apiVersion: apps/v1
kind: Deployment
metadata:
  name: <%= title %>
  namespace: <%= namespace %>
  labels:
    product: <%= product %>
    app: <%= title %>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <%= title %>
  template:
    metadata:
      labels:
        app: <%= title %>
        product: <%= product %>
    spec:
      imagePullSecrets:
        - name: <%= product %>-acr-secret
      containers:
        - name: <%= title %>
          image: "__DOCKER_IMAGE_NAME__"
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: <%= title %>-configmap
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 150m
              memory: 512Mi
