apiVersion: v1
kind: Service
metadata:
  name: <%= title %>-service
  namespace: <%= namespace %>
  labels:
    app: <%= title %>

spec:
  type: ClusterIP
  selector:
    app: <%= title %>
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000