// eslint-disable-next-line import/no-anonymous-default-export
export default {
  "/dashboard": "./dashboard",
  "/tasklist/all_task": "./all_task",
  "/tasklist/all_task/*": "./all_task_id",
  "/tasklist/my_task": "./my_task",
  "/tasklist/my_task/*": "./my_task_id",
  "/tasklist/my_group_task": "./my_group_task",
  "/tasklist/my_group_task/*": "./my_group_task_id",
  "/bpmn/*": "./bpmn",
  "/create-workflow/bpmn": "./bpmn",
  "/create-workflow/dmn": "./dmn",
  "/decision/decision-definitions": "./decision-definitions",
  "/decision/decision-definitions/*": "./decision-definitions_details",
  "/process/deployments": "./deployments",
  "/create-workflow/form": "./form",
  "/process/process-definitions": "./process-definitions",
  "/process/process-definitions/*": "./process-definitions_details",
  "/groups": "./groups",
  "/groups/*": "./groupId",
  "/forms": "./forms",
  "/forms/*": "./formId",
  "/anchor-flow": "./sidebarLayout",
};
