name: Push Stable Image to ACR
on:
  workflow_dispatch:
    inputs:
      stable_image:
        description: "Enter the stable Image tag to push"
        required: true
        default: ""

env:
  CONTAINER_REGISTRY: maerskao.azurecr.io
  
jobs:
  set-image-tag:
    runs-on: ubuntu-20.04
    outputs:
      image-tag: ${{ steps.image_tag.outputs.IMAGE_TAG }}
    steps:
      - id: image_tag
        run: echo "##[set-output name=IMAGE_TAG;]$(echo ${{env.CONTAINER_REGISTRY}}/anchor-flow-stable:${{github.event.inputs.stable_image}})"
  build:
    runs-on: ubuntu-20.04
    needs: set-image-tag
    environment: dev
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Print Image Tag
        run: echo 'Image Tag is' ${{ needs.set-image-tag.outputs.image-tag }}
        
      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v1.6.0
        
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{env.CONTAINER_REGISTRY}}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PWD }}
          logout: true
      - name: Build and Push Docker image to Azure Container Registry
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          tags: ${{ needs.set-image-tag.outputs.image-tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
